name: Build Signed AAB (with Name Change)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      - name: 2. Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: 3. Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # ⬇️===== FIX: Ab yeh KEYSTORE_PASSWORD check karega =====⬇️
      - name: 4. Check Secrets
        run: |
          if [ -z "${{ secrets.KEYSTORE_BASE64 }}" ]; then
            echo "::error:: SECRET 'KEYSTORE_BASE64' NOT SET."
            exit 1
          fi
          if [ -z "${{ secrets.KEY_ALIAS }}" ]; then
            echo "::error:: SECRET 'KEY_ALIAS' NOT SET."
            exit 1
          fi
          if [ -z "${{ secrets.KEY_PASSWORD }}" ]; then
            echo "::error:: SECRET 'KEY_PASSWORD' NOT SET."
            exit 1
          fi
          if [ -z "${{ secrets.KEYSTORE_PASSWORD }}" ]; then
            echo "::error:: SECRET 'KEYSTORE_PASSWORD' NOT SET."
            exit 1
          fi
          echo "All secrets are set. Proceeding with build."

      - name: 5. Change Package Name
        run: |
          echo "Changing package name from com.example.chetegram to com.opkukna1.exambeing..."
          sed -i 's/com.example.chetegram/com.opkukna1.exambeing/g' android/app/build.gradle.kts
        working-directory: ${{ github.workspace }}

      - name: 6. Get Flutter dependencies
        run: flutter pub get
      
      - name: 7. Decode Keystore
        run: |
          echo "Decoding Keystore..."
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/upload-keystore.jks
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      - name: 8. Create key.properties file
        run: |
          echo "Creating key.properties file..."
          echo "storeFile=upload-keystore.jks" > android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          # ⬇️===== FIX: Ab yeh KEYSTORE_PASSWORD ka istemal karega =====⬇️
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/key.properties
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          # ⬇️===== FIX: Yahaan bhi badal diya =====⬇️
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }} 

      - name: 9. Build Signed App Bundle
        run: flutter build appbundle --release

      - name: 10. Upload AAB as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-appbundle
          path: build/app/outputs/bundle/release/app-release.aab
