name: Build Flutter App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      - name: 2. Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: 3. Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: 4. Get Flutter dependencies
        run: flutter pub get

      - name: 5. Build APK
        run: flutter build apk --release

      - name: 6. Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
