name: Build Flutter APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: Clean old builds and cache
        run: |
          flutter clean
          flutter pub cache repair
          rm -rf android/.gradle
          rm -rf android/build
          rm -rf build

      # 🧩 Recreate platform files if missing (Main fix)
      - name: Recreate platform files if missing
        run: |
          if [ ! -d "android" ]; then
            echo "Android folder missing. Creating new platform files..."
            flutter create .
          else
            echo "Android folder already exists. Skipping create step."
          fi

      - name: Get dependencies
        run: flutter pub get

      - name: Verify pubspec
        run: flutter pub deps

      - name: Generate App Icons
        run: flutter pub run flutter_launcher_icons

      - name: Build Release APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
