name: Build Flutter APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
          cache: true

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Clean project
        run: flutter clean

      - name: Force-Regenerate Android Project
        run: echo "Regenerating Android project..." && rm -rf android && flutter create --platforms=android .

      - name: Update Kotlin version
        run: chmod +x .github/scripts/update_kotlin.sh && ./.github/scripts/update_kotlin.sh

      - name: TEMPORARY FIX - Remove problem plugins
        run: sed -i -e '/pdfx/d' -e '/smart_auth/d' pubspec.yaml && echo "Removed pdfx and smart_auth plugins."

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Run widget tests
        run: flutter test

      - name: Generate App Icons
        run: flutter pub run flutter_launcher_icons

      - name: Build Release APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
